### ISSUE TITLE
[diagram] diagram does not openon windows

### ISSUE THREAD

**Issue by JanKoehnlein** [yang-tools/yang-eclipse#15]
From the log:
```
Caused by: java.lang.IllegalArgumentException: Illegal secondary id (cannot be empty or contain a colon)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4314)
	at io.typefox.yang.eclipse.diagram.OpenDiagramHandler.openDiagram(OpenDiagramHandler.java:88)
	at io.typefox.yang.eclipse.diagram.OpenDiagramHandler.execute(OpenDiagramHandler.java:41)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 36 more
```

The secondary ID of a view in Eclipe is not allowed to contain a colon, which automatically happens on windows as we take the file URI's path, i.e. `file:///C:/some/path/somefile.yang` -> `C:/some/path/somefile.yang`.

We should encode the URIs colons.

**Comment by JanKoehnlein** [comment]
More trouble ahead: The only viable option as a backend for SWT's browser widget on windows is Internet Explorer. So we have to backport sprotty to IE11.

**Comment by JanKoehnlein** [comment]
Finally fixed.
